<div class="row">
	
	<div class="adMnIdL col-lg-offset-3 col-md-offset-3 col-sm-offset-3  col-xs-offset-0 col-lg-6 col-xs-12 col-md-6 col-sm-6">
            
		<div class="clearfix" id="userRegForm">
			<div>
				<h3 class="text-center">
					Institute Management<sup><a
						href="<?php echo $this->url('institute/list'); ?>"> <i
							class="fa fa-list-alt"></i>
					</a></sup>
				</h3>

			</div>

			<div
				class="col-md-12 col-sm-12 col-xs-12">
                            <div class="box box-primary">
                                <br>
		
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form');
$form->setAttribute('role', 'form');
$form->setAttribute('autocomplete', 'off');
echo $this->form()->openTag($form);
?>
                            <div class="form-group">
    <label for="exampleInputEmail1">Name of Institute</label>
<?php

$name = $form->get('name');
echo $this->formtext($name);
echo $this->formelementerrors($name);
?>
    </div>
                                
    <div class="form-group">
    <label for="exampleInputEmail1">Id of Institute</label>
<?php

$institudeAutoId = $form->get('institudeAutoId');
echo $this->formtext($institudeAutoId);
echo $this->formelementerrors($institudeAutoId);
?>
    </div>
    <div class="form-group">
    <label for="exampleInputEmail1">Status</label>
<?php

$status = $form->get('enabled');
echo $this->formselect($status);

?>
    </div>
                            <div class="form-group">
    <label for="exampleInputEmail1">Institute's Email ID</label>
<?php

$emailId = $form->get('emailId');
echo $this->formemail($emailId);
echo $this->formelementerrors($emailId);
?>
    </div>
    <div class="form-group">
    <label for="exampleInputEmail1">Institute's Alternate Email ID</label>
<?php

$emailIdTwo = $form->get('emailIdTwo');
echo $this->formemail($emailIdTwo);
echo $this->formelementerrors($emailIdTwo);
?>
    </div>
    <div class="form-group">
    <label for="exampleInputEmail1">Phone Number</label>
<?php

$phoneNumber = $form->get('phoneNumber');
echo $this->formnumber($phoneNumber);
echo $this->formelementerrors($phoneNumber);
?>
    </div>
    <div class="form-group">
    <label for="exampleInputEmail1">Alternate Phone Number 1</label>
<?php

$phoneNumberTwo = $form->get('phoneNumberTwo');
echo $this->formnumber($phoneNumberTwo);
echo $this->formelementerrors($phoneNumberTwo);
?>
    </div>
    <div class="form-group">
    <label for="exampleInputEmail1">Alternate Phone Number 2</label>
<?php

$phoneNumberThree = $form->get('phoneNumberThree');
echo $this->formnumber($phoneNumberThree);
echo $this->formelementerrors($phoneNumberThree);
?>
    </div>
    <div class="form-group">
    <label for="exampleInputEmail1">Zip Code</label>
<?php

$pincode = $form->get('pincode');
echo $this->formnumber($pincode);
echo $this->formelementerrors($pincode);
?>
    </div>
    <div class="form-group">
    <label for="exampleInputEmail1">Country</label>
<?php

$country = $form->get('country');
echo $this->formselect($country);

?>
    </div>
   
<?php

$csrf = $form->get('mcsrf');
echo $this->formhidden($csrf);
echo $this->formElementErrors($csrf);

?>
		

		<div class="form-group">
					<div class="control-group">
						<div class="controls col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4 col-sm-offset-4 col-sm-4">
							<button class="btn btn-primary btn-block">Save</button>
                                                        <br>
						</div>
					</div>
				</div>
		<?php
echo $this->form()->closeTag();
?>
		</div>

		</div>
	</div>
        </div>
</div>

