<div class="row">
	<div class="adMnIdL col-lg-offset-3 col-md-offset-3 col-sm-offset-3  col-xs-offset-0 col-lg-6 col-xs-12 col-md-6 col-sm-6">
	<?php
$instInfo = $this->instInfo;
?>
		<h3 class="text-center">
			Fee Structure for <?php echo $instInfo['name']?><sup><a
				href="/institute/listcomponents"> <i class="fa fa-list-alt"></i>
			</a></sup>
		</h3>
		<div class="row" id="userRegForm">
			<div class="col-md-12 col-sm-12 col-xs-12">
                            <div class="box box-primary">
		

<?php
$allFields = $this->allFields;
$form = $this->form;
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form');
$form->setAttribute('role', 'form');
$form->setAttribute('autocomplete', 'off');
echo $this->form()->openTag($form);
?>

<?php
foreach ($allFields as $key) {
    echo '<div class="well well-sm">';
    $amt = $key . 'amount';
    $act = $key . 'action';
    
    $keyE = $form->get($key);
    echo '<div class="form-group"><label for="exampleInputEmail1">Component</label>'.$this->formtext($keyE);
    echo $this->formelementerrors($keyE).'</div>';
    
    $acte = $form->get($act);
    echo '<div class="form-group"><label for="exampleInputEmail1">Status</label>'.$this->formselect($acte).'</div>';
    
    $amte = $form->get($amt);
    echo '<div class="form-group"><label for="exampleInputEmail1">Amount</label>'.$this->forminput($amte);
    echo $this->formelementerrors($amte).'</div>';
    echo "</div>";
}

$csrf = $form->get('mcsrf');
echo $this->formhidden($csrf);
echo $this->formElementErrors($csrf);

?>
		

		<div class="form-group">
					<div class="control-group">
						<div class="controls col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4 col-sm-offset-4 col-sm-4">
							<button class="btn btn-primary btn-block">Save</button>
						</div>
					</div>
				</div>
		<?php
echo $this->form()->closeTag();
?>
		</div>

		</div>
                </div>
	</div>
</div>

