<div class="row">
	<div class="adMnIdL col-lg-12 col-xs-12 col-md-12 col-sm-12">
	<?php
use Application\Entity\Student;
echo $this->headLink()->prependStylesheet($this->basePath('css/dataTables.bootstrap.min.css'));

?>
<div class="row">
			<div class="col-lg-12">
                            <h3 class="text-center">Student Listing</h3> 
                            
			<?php
if (! empty($instituteId)) {
    $instituteId = $this->instituteId;
    $institute = $this->instituteInfo;
    ?>
			    <a class="btn btn-xs btn-block btn-info"
					href="<?php echo $this->url('agent/list',array('instituteId'=>$instituteId)); ?>">List
					Agents <i class="fa fa-list-alt"></i>
				</a>
				<h4 class="text-center"><?php echo $institute['name']?></h4>
				<?php
    $agInfo = $this->agentInfo;
    if (! empty($agInfo)) {
        ?>
				    <h6 class="text-center"><?php echo $agInfo['name']?></h6>
				    <?php
    }
    ?>
			    <?php
}
?>
<?php

$allStudents = $this->allStudents;
if (! empty($allStudents)) {
    
    ?>
                                    <div class="box box-primary">
                                    <table id="allStudentsData456"
					class="table table-striped table-bordered" cellspacing="0"
					width="100%">
					<thead>
						<tr>
							<th>Name</th>
							<th>Contact Number</th>
							<th>Institute</th>
							<th>Programme</th>
							<th>Agent</th>
							<th>Fee Details</th>
						</tr>
					</thead>
					<tfoot>
						<tr>
							<th>Name</th>
							<th>Contact Number</th>
							<th>Institute</th>
							<th>Programme</th>
							<th>Agent</th>
							<th>Fee Details</th>
						</tr>
					</tfoot>


					<tbody>
	<?php
    foreach ($allStudents as $student) {
        $student instanceof Student;
        $studentId = $student->getId();
        $cmPercentage = $student->getAgent()->getCommissionPercentage();
        $courseFees = $student->getProgramme()->getFeeAmount();
        $courseFeeCurrency = $student->getProgramme()->getFeeCurrency();
        $defaultComsn = (($cmPercentage / 100) * ($courseFees));
        $cmsToPePaid = $student->getCommissionToBePaidByInstitute();
        $morEleId = 'feeChart' . $student->getId();
        $status = $student->getCommissionStatus();
        if ($status == 0) {
            $class = "alert-danger";
            $status = 'PENDING';
        } else {
            $status = 'PAID';
            $class = "alert-success";
        }
        $statData = array(
            "element" => $morEleId,
            "data" => array(
                array(
                    'label' => 'Agent Commission',
                    'value' => $cmsToPePaid
                ),
                array(
                    'label' => 'Remaining Fees',
                    'value' => $courseFees - $cmsToPePaid
                )
            )
        );
        ?><tr class="items" id="<?php echo $studentId;?>">

							<td> <?php
        echo $student->getName()?>&nbsp;<a
								class="btn btn-xs btn-success"
								href="<?php
        echo $this->url('student/update', array(
            'studentId' => $student->getId()
        ));
        ?>"><i class="fa fa-pencil-square-o"></i> </a>&nbsp;<a
								class="btn btn-xs btn-info"
								href="<?php
        echo $this->url('student/details', array(
            'studentId' => $student->getId()
        ));
        ?>"><i class="fa fa-eye"></i></a></td>
							<td><?php echo $student->getMobile()?></td>
							<td> <?php
        echo ucwords($student->getProgramme()
            ->getInstitute()
            ->getName())?></td>
							<td>
								<?php
        echo $student->getProgramme()->getName()?></p>
							</td>
							<td>
        <?php
        echo $student->getAgent()->getName()?>
							<a class="btn btn-xs"
								href="<?php echo $this->url('agent/details',array('agentId'=>$student->getAgent()->getId())); ?>"><i
									class="fa fa-eye"></i> </a> <?php
        ?></td>
							<td>
								<ol>
									<li>Tuition <?php
        echo ':' . $this->currencyFormat($student->getFeeAmount(), $student->getFeeCurrency())?></li>
							<?php
        $feeInfo = $this->feeInfoForSTudent[$student->getId()];
        $breakDowns = $feeInfo['breakDowns'];
        $structOptions = $feeInfo['structOptions'];
        $currency = $student->getProgramme()->getFeeCurrency();
        $breakDownTotal = 0;
        if (! empty($breakDowns)) {
            
            foreach ($breakDowns as $breakDown) {
                @$amt = $breakDown['amount'];
                @$breakDownTotal = $breakDownTotal + $amt;
                @$amt = $this->currencyFormat($amt, $currency, false, LOCALE);
                echo '<li>' . @$structOptions[$breakDown['componentId']]['name'] . ': ' . @$amt . '</li>';
            }
        }
        ?>
								
								</ol> <strong>Total Fees: <?php
        $feeAtTimeOfEnrollment = $student->getFeeAmount();
        $totalFees = $feeAtTimeOfEnrollment + $breakDownTotal;
        echo $this->currencyFormat($totalFees, $currency, false, LOCALE);
        ?></strong>
                                                           
                                                            <a class="btn btn-xs"
								href="<?php echo $this->url('student/feedetails',array('studentId'=>$student->getId())) ?>"><i
									class="fa fa-eye"></i> </a> 
							</td>

						</tr>
<?php }?>
	</tbody>
				</table>
                                    </div>
			</div><?php }else{?>
				<h1 class="text-center">No Students have been registered so far</h1>
				<?php }?> 
	</div>
	</div>
</div>
</div>
<?php
if (ENABLE_DATATABLES) {
    echo $this->headScript()
        ->prependFile($this->basePath('js/dataTables.bootstrap.min.js'))
        ->prependFile($this->basePath('js/jquery.dataTables.min.js'));
    
    ?>
<script type="text/javascript">

$(document).ready(function() {
    $('#allStudentsData456').DataTable();
} );
</script>
<?php }?>

