<?php
$instituteDetails = $this->instituteDetails;
?>
<div class="row">
    <div class="adMnIdL col-lg-offset-3 col-md-offset-3 col-sm-offset-3  col-xs-offset-0 col-lg-6 col-xs-12 col-md-6 col-sm-6">
        
            <div id="userRegForm">


                <div
                    class="col-md-12 col-sm-12 col-xs-12">
                    
                    <h3 class="text-center">
                        Programme Management<a
                            href="<?php echo $this->url('programme/list', array('instituteId' => $instituteDetails['id'])); ?>">
                            <i class="fa fa-list-alt"></i>
                        </a>
                    </h3>
                    <h5 class="text-center"><i class="fa fa-university"></i>(<?php echo ucwords($instituteDetails['name']) ?>)</h5>

                    <div class="box box-primary clearfix">
                        <br>

                    <?php
                    $form = $this->form;
                    $form->prepare();
                    $form->setAttribute('method', 'post');
                    $form->setAttribute('class', 'form');
                    $form->setAttribute('role', 'form');
                    $form->setAttribute('autocomplete', 'off');
                    echo $this->form()->openTag($form);
                    ?>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Name of Programme</label>
                        <?php
                        $name = $form->get('name');
                        echo $this->formtext($name);
                        echo $this->formelementerrors($name);
                        ?>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Status</label>
                        <?php
                        $status = $form->get('enabled');
                        echo $this->formselect($status);
                        ?>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Abbreviation</label>
<?php
$abbreviation = $form->get('abbreviation');
echo $this->forminput($abbreviation);
echo $this->formelementerrors($abbreviation);
?>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Fees For This Course</label>
                        <?php
                        $feeAmount = $form->get('feeAmount');
                        echo $this->formnumber($feeAmount);
                        echo $this->formelementerrors($feeAmount);
                        ?>
                    </div>
                    <div class="form-group">
                        <label for="exampleInputEmail1">Fee Currency</label>
                        <?php
                        $feeCurrency = $form->get('feeCurrency');
                        echo $this->formselect($feeCurrency);
                        ?>
                    </div>
                        <?php
                        $csrf = $form->get('mcsrf');
                        echo $this->formhidden($csrf);
                        echo $this->formElementErrors($csrf);
                        ?>


                    <div class="form-group">
                        <div class="control-group">
                            <br>
                            <div class="controls col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4 col-sm-offset-4 col-sm-4">
                                <button class="btn btn-primary btn-block">Save</button>
                                <br>
                            </div>
                        </div>
                    </div>
<?php
echo $this->form()->closeTag();
?>
                </div>

            </div>
        </div>
    </div>
</div>
