<div class="row">
<?php
$instituteInfo= $this->instituteInfo;
?><?php

$form = $this->form;
$form->prepare();
$form->setAttribute('method', 'post');
$form->setAttribute('class', 'form');
$form->setAttribute('role', 'form');
$form->setAttribute('autocomplete', 'off');
echo $this->form()->openTag($form);
?>
	<div class="adMnIdL col-lg-offset-3 col-md-offset-3 col-sm-offset-3  col-xs-offset-0 col-lg-6 col-xs-12 col-md-6 col-sm-6">
		<div class="row" id="userRegForm">

			<div class="col-md-12 col-sm-12 col-xs-12">
				<h3 class="text-center">Agent Registration for <?php echo $instituteInfo['name'];?></h3>
				
                                <div class="box box-primary"> 
                                    <br>
				<div class="form-group">
                        <label for="exampleInputEmail1">Select Agent</label>
                                        <?php
    
    $agentId = $form->get('agentId');
    echo $this->formselect($agentId);
    
    ?></div>
                                <div class="form-group">
                        <label for="exampleInputEmail1">Commission Percentage %</label>
        <?php

    $commission = $form->get('commissionPercentage');
    echo $this->formnumber($commission);
    echo $this->formelementerrors($commission);
    ?></div>
        <?php

    $csrf = $form->get('mcsrf');
    echo $this->formhidden($csrf);
    echo $this->formElementErrors($csrf);
    
    ?>
                        <div class="form-group">
                        <label for="exampleInputEmail1">Status</label>
<?php

    $status = $form->get('enabled');
    echo $this->formselect($status);
    
    ?>	</div><div class="form-group">
					<div class="control-group">
						<div class="controls col-md-4 col-md-offset-4 col-lg-4 col-lg-offset-4 col-sm-offset-4 col-sm-4">
                                                    <br>
                                                    <button class="btn btn-primary btn-block">Save</button>
                                                        <br>
						</div>
					</div>
				</div>
<?php
echo $this->form()->closeTag();
?>
				
			</div>
                        </div>
		</div>
	</div>

</div>
